apps/users/urls.py
from django.urls import path



from apps.users.views import (
    UserPositionCreateView,
    UserPositionListView,
    UserPositionUpdateView,
    AdminDashboardView,
    UserTeamCreateView,
    UserTeamListView,
    UserTeamUpdateView,
    UserProjectJoinedCreateView,
    UserProjectJoinedListView,
    UserProjectJoinedUpdateView,
    UserMemberCreateView,
    UserMemberListView,
    UserExportCSVCreateView,
    SignUpView,
    SignInView,
    SignOutView,
    UserMemberUpdateView
)

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signin/', SignInView.as_view(), name='signin'),
    path('signout/', SignOutView.as_view(), name='signout'),
    # path('user/<int:id>/change-role/', ChangeRoleUserView.as_view(), name='change-role'),
    path('member/add/', UserMemberCreateView.as_view(), name='member-add'),
    path('members/', UserMemberListView.as_view(), name='member-list'),
    path('member/<int:id>/edit/', UserMemberUpdateView.as_view(), name='member-update'),
    path('dashboard/', AdminDashboardView.as_view(), name='dashboard'),
    path('position/add/', UserPositionCreateView.as_view(), name='position-add'),
    path('position/<int:id>/edit/', UserPositionUpdateView.as_view(), name='position-update'),
    path('positions/', UserPositionListView.as_view(), name='position-list'),
    path('teams/', UserTeamListView.as_view(), name='team-list'),
    path('team/add/', UserTeamCreateView.as_view(), name='team-add'),
    path('team/<int:id>/edit/', UserTeamUpdateView.as_view(), name='team-update'),
    path('project-joined/add/', UserProjectJoinedCreateView.as_view(), name='project-joined-add'),
    path('projects-joined/', UserProjectJoinedListView.as_view(), name='project-joined-list'),
    path('project-joined/<int:id>/edit/', UserProjectJoinedUpdateView.as_view(), name='project-joined-update'),
    path('export/', UserExportCSVCreateView.as_view(), name='export')
]

mms/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/base/models.py
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    delete_flg = models.BooleanField(default=False)

    class Meta:
        abstract = True

apps/base/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Bootstrap Admin Theme v3</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- styles -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body>
{% include 'includes/headers.html' %}
<div class="page-content" style="position: relative;">
    <div class="row">
        <div class="col-md-2">
            <div class="sidebar content-box" style="display: block;">
                <ul class="nav">
                    <!-- Main menu -->
                    <li class="current"><a href="index.html"><i class="glyphicon glyphicon-home"></i> Dashboard</a></li>
                    <li class="submenu">
                        <a href="{% url 'users:position-list' %}">
                            <i class="glyphicon glyphicon-list"></i>Position
                            <span class="caret pull-right"></span>
                        </a>
                        <ul>
                            <li><a href="{% url 'users:position-list' %}">List</a></li>
                            <li><a href="{% url 'users:position-add' %}">Create</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="{% url 'users:member-list' %}">
                            <i class="glyphicon glyphicon-user"></i>Member
                            <span class="caret pull-right"></span>
                        </a>
                        <ul>
                            <li><a href="{% url 'users:member-list' %}">List</a></li>
                            <li><a href="{% url 'users:member-add' %}">Create</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="{% url 'users:team-list' %}">
                            <i class="glyphicon glyphicon-stats"></i>Team
                            <span class="caret pull-right"></span>
                        </a>
                        <ul>
                            <li><a href="{% url 'users:team-list' %}">List</a></li>
                            <li><a href="{% url 'users:team-add' %}">Create</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="{% url 'users:team-list' %}">
                            <i class="glyphicon glyphicon-stats"></i>Project joined
                            <span class="caret pull-right"></span>
                        </a>
                        <ul>
                            <li><a href="{% url 'users:project-joined-list' %}">List</a></li>
                            <li><a href="{% url 'users:project-joined-add' %}">Create</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-10">
            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>

<footer>
    <div class="container">

        <div class="copy text-center">
            Copyright 2020 <a href='#'>Website</a>
        </div>

    </div>
</footer>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- Custom js -->
<script src="{% static 'js/custom.js' %}"></script>
{% block custom_js %}{% endblock %}
</body>
</html>