apps/users/urls.py
from django.urls import path



from apps.users.views import (
    UserPositionCreateView,
    UserPositionListView,
    UserPositionUpdateView,
    AdminDashboardView,
    UserTeamCreateView,
    UserTeamListView,
    UserTeamUpdateView,
    UserProjectJoinedCreateView,
    UserProjectJoinedListView,
    UserProjectJoinedUpdateView,
    UserMemberCreateView,
    UserMemberListView,
    UserExportCSVCreateView,
    SignUpView,
    SignInView,
    SignOutView,
    UserMemberUpdateView
)

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signin/', SignInView.as_view(), name='signin'),
    path('signout/', SignOutView.as_view(), name='signout'),
    # path('user/<int:id>/change-role/', ChangeRoleUserView.as_view(), name='change-role'),
    path('member/add/', UserMemberCreateView.as_view(), name='member-add'),
    path('members/', UserMemberListView.as_view(), name='member-list'),
    path('member/<int:id>/edit/', UserMemberUpdateView.as_view(), name='member-update'),
    path('dashboard/', AdminDashboardView.as_view(), name='dashboard'),
    path('position/add/', UserPositionCreateView.as_view(), name='position-add'),
    path('position/<int:id>/edit/', UserPositionUpdateView.as_view(), name='position-update'),
    path('positions/', UserPositionListView.as_view(), name='position-list'),
    path('teams/', UserTeamListView.as_view(), name='team-list'),
    path('team/add/', UserTeamCreateView.as_view(), name='team-add'),
    path('team/<int:id>/edit/', UserTeamUpdateView.as_view(), name='team-update'),
    path('project-joined/add/', UserProjectJoinedCreateView.as_view(), name='project-joined-add'),
    path('projects-joined/', UserProjectJoinedListView.as_view(), name='project-joined-list'),
    path('project-joined/<int:id>/edit/', UserProjectJoinedUpdateView.as_view(), name='project-joined-update'),
    path('export/', UserExportCSVCreateView.as_view(), name='export')
]

mms/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/users/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import UserManager
from django.contrib.postgres.fields import ArrayField
from django.db import models
from apps.base.models import BaseModel


class UserPosition(BaseModel):
    name = models.CharField(max_length=256, unique=True)
    short_name = models.CharField(max_length=128)

    class Meta:
        db_table = 'user_position'


class UserTeam(BaseModel):
    name = models.CharField(max_length=128)
    description = models.TextField()
    leader = models.CharField(max_length=150)

    class Meta:
        db_table = 'user_team'


class UserProjectJoined(BaseModel):
    MAX_TEAM_SIZE = 50

    name = models.CharField(max_length=256, unique=True)
    short_name = models.CharField(max_length=128)
    start_date = models.DateField()
    end_date = models.DateField()
    project_leader = models.CharField(max_length=150)
    members = ArrayField(models.CharField(max_length=10, blank=True), size=MAX_TEAM_SIZE)

    class Meta:
        db_table = 'user_project_joined'


class User(AbstractBaseUser, BaseModel):
    ROLE_ADMIN = 0
    ROLE_MEMBER = 1
    USER_ROLES = (
        (ROLE_ADMIN, 'Sun Admin'),
        (ROLE_MEMBER, 'Sun Member'),
    )

    username = models.CharField(_('username'), max_length=150, unique=True)
    email = models.EmailField(_('email address'), blank=True, null=True, unique=True)
    role = models.IntegerField(choices=USER_ROLES, default=ROLE_MEMBER)
    is_activate = models.BooleanField(default=False)
    position = models.ForeignKey(UserPosition, on_delete=models.CASCADE, null=True)
    team = models.ForeignKey(UserTeam, on_delete=models.CASCADE, null=True)
    user_project_joined = models.ManyToManyField(UserProjectJoined, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = UserManager()

    class Meta:
        db_table = 'user'

    def __str__(self):
        return 'User: {}'.format(self.username)


class UserSkill(BaseModel):
    LEVELS = (
        (0, 'Junior'),
        (1, 'Middle 1'),
        (2, 'Middle 2'),
        (3, 'Senior'),
    )
    name = models.CharField(max_length=128)
    level = models.IntegerField(choices=LEVELS, default=LEVELS[0][0])
    years_experience = models.IntegerField(default=1)
    user = models.ManyToManyField(User)

    class Meta:
        db_table = 'user_skill'

apps/users/forms.py
from django import forms
from django.contrib.auth import authenticate

from apps.users.models import (
    UserPosition,
    UserProjectJoined,
    UserTeam,
    UserSkill,
    User
)


class UserPositionCreatUpdateForm(forms.ModelForm):
    class Meta:
        model = UserPosition
        fields = ['name', 'short_name']


class UserProjectJoinedCreateUpdateForm(forms.ModelForm):
    members = forms.CharField()

    class Meta:
        model = UserProjectJoined
        fields = ['name', 'short_name', 'start_date', 'end_date', 'project_leader']


class UserTeamCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = UserTeam
        fields = ['name', 'description', 'leader']


class UserMemberCreateUpdateForm(forms.ModelForm):
    skills = forms.CharField()

    class Meta:
        model = User
        fields = ['username',
                  'email',
                  'role',
                  'is_activate',
                  'position',
                  'team',
                  'skills']

    def clean(self):
        super().clean()
        data = self.cleaned_data
        username = data.get('password')
        user = User.objects.filter(username=username).exists()
        if user:
            raise forms.ValidationError("User already exists")


class UserSkillCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = UserSkill
        fields = ['name', 'level', 'years_experience']


class UserExportCSVCreateForm(forms.Form):
    export_position = forms.BooleanField(required=False)
    # export_skill = forms.BooleanField(required=False)
    export_team = forms.BooleanField(required=False)


class SignUpForm(forms.Form):
    email = forms.EmailField(max_length=100)
    password = forms.CharField(max_length=256)
    password1 = forms.CharField(max_length=256)

    def clean(self):
        super().clean()
        data = self.cleaned_data
        password = data.get('password')
        password1 = data.get('password1')
        if password != password1:
            raise forms.ValidationError("Password & Password Confirm not matching!")

        if User.objects.filter(email=data.get('email')).exists():
            raise forms.ValidationError("User already exists")


class SignInForm(forms.Form):
    email = forms.EmailField(max_length=100)
    password = forms.CharField(max_length=256)

    def clean(self):
        super().clean()
        data = self.cleaned_data
        password = data.get('password')
        email = data.get('email')
        user = authenticate(username=email, password=password)
        if not user:
            raise forms.ValidationError("Email & Password not matching!")

apps/users/views.py
import csv
import datetime
import os
import json

from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.conf import settings
from django.contrib.auth import authenticate, login, logout

from apps.users.forms import (
    UserPositionCreatUpdateForm,
    UserTeamCreateUpdateForm,
    UserProjectJoinedCreateUpdateForm,
    UserSkillCreateUpdateForm,
    UserMemberCreateUpdateForm,
    UserExportCSVCreateForm,
    SignUpForm,
    SignInForm
)
from apps.users.models import (
    UserPosition,
    UserTeam,
    UserProjectJoined,
    UserSkill,
    User
)

from apps.users.decorators import admin_required

DEFAULT_PASSWORD = 'Aa@123456'


class AdminDashboardView(View):
    template_name = 'base.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})


class UserPositionCreateView(View):
    template_name = 'user/position/position_add.html'
    form_class = UserPositionCreatUpdateForm

    @method_decorator(admin_required)
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

    @method_decorator(admin_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('users:position-list'))
        return render(request, self.template_name, {'form': form})


class UserPositionListView(View):
    template_name = 'user/position/position_list.html'
    paginate_by = 10

    @method_decorator(admin_required)
    def get(self, request, *args, **kwargs):
        positions = UserPosition.objects.filter(delete_flg=False).order_by('name')
        paginator = Paginator(positions, self.paginate_by)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, self.template_name, {'positions': page_obj})


class UserPositionUpdateView(View):
    template_name = 'user/position/position_edit.html'
    form_class = UserPositionCreatUpdateForm

    @method_decorator(admin_required)
    def get(self, request, *args, **kwargs):
        position_id = kwargs.get('id')
        position = UserPosition.objects.filter(id=position_id).first()
        if not position:
            return render(request, '404.html', {})
        return render(request, self.template_name, {'position': position})

    @method_decorator(admin_required)
    def post(self, request, *args, **kwargs):
        position_id = kwargs.get('id')
        position = UserPosition.objects.filter(id=position_id).first()
        if not position:
            return render(request, '404.html', {})
        form = self.form_class(request.POST, instance=position)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('users:position-list'))
        return render(request, self.template_name, {'form': form, 'position_id': position_id})


class UserTeamCreateView(View):
    template_name = 'user/team/team_add.html'
    form_class = UserTeamCreateUpdateForm

    @method_decorator(admin_required)
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

    @method_decorator(admin_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('users:team-list'))
        return render(request, self.template_name, {'form': form})


class UserTeamListView(View):
    template_name = 'user/team/team_list.html'
    paginate_by = 10

    @method_decorator(admin_required)
    def get(self, request, *args, **kwargs):
        teams = UserTeam.objects.filter(delete_flg=False).order_by('name')
        paginator = Paginator(teams, self.paginate_by)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, self.template_name, {'teams': page_obj})


class UserTeamUpdateView(View):
    template_name = 'user/team/team_edit.html'
    form_class = UserTeamCreateUpdateForm

    def dispatch(self, request, *args, **kwargs):
        team_id = kwargs.get('id')
        self.team = UserTeam.objects.filter(id=team_id).first()
        if not self.team:
            return render(request, '404.html', {})
        return super().dispatch(request, *args, **kwargs)

    @method_decorator(admin_required)
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'team': self.team})

    @method_decorator(admin_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, instance=self.team)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('users:team-list'))
        return render(request, self.template_name, {'form': form, 'team_id': kwargs.get('id')})


class UserProjectJoinedCreateView(View):
    template_name = 'user/project_joined/project_joined_add.html'
    form_class = UserProjectJoinedCreateUpdateForm

    @method_decorator(admin_required)
    def get(self, request, *args, **kwargs):
        teams = UserTeam.objects.filter(delete_flg=False)
        return render(request, self.template_name, {'teams': teams})

    @method_decorator(admin_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            members = form.cleaned_data['members']
            form.cleaned_data['members'] = members.split(';')
            obj = UserProjectJoined(**form.cleaned_data)
            obj.save()
            return redirect(reverse_lazy('users:project-joined-list'))
        return render(request, self.template_name, {'form': form})


class UserProjectJoinedListView(View):
    template_name = 'user/project_joined/project_joined_list.html'
    paginate_by = 10

    @method_decorator(admin_required)
    def get(self, request, *args, **kwargs):
        project_joined = UserProjectJoined.objects.filter(delete_flg=False).order_by('name')
        paginator = Paginator(project_joined, self.paginate_by)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, self.template_name, {'projects_joined': page_obj})


class UserProjectJoinedUpdateView(View):
    template_name = 'user/project_joined/project_joined_update.html'
    form_class = UserProjectJoinedCreateUpdateForm

    def dispatch(self, request, *args, **kwargs):
        project_joined_id = kwargs.get('id')
        self.project_joined = UserProjectJoined.objects.filter(id=project_joined_id).first()
        if not self.project_joined:
            return render(request, '404.html', {})
        return super().dispatch(request, *args, **kwargs)

    @method_decorator(admin_required)
    def get(self, request, *args, **kwargs):
        teams = UserTeam.objects.filter(delete_flg=False)
        return render(request, self.template_name, {'project_joined': self.project_joined, 'teams': teams})

    @method_decorator(admin_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, instance=self.project_joined)
        if form.is_valid():
            members = form.cleaned_data['members']
            form.cleaned_data['members'] = members.split(';')
            self.project_joined.__dict__.update(**form.cleaned_data)
            self.project_joined.save()
            return redirect(reverse_lazy('users:project-joined-list'))
        return render(request, self.template_name, {'form': form, 'project_joined_id': kwargs.get('id')})


class UserMemberCreateView(View):
    template_name = 'user/member/member_add.html'
    form_class = UserMemberCreateUpdateForm

    def dispatch(self, request, *args, **kwargs):
        teams = UserTeam.objects.filter(delete_flg=False)
        positions = UserPosition.objects.filter(delete_flg=False)
        user_project_joined = UserProjectJoined.objects.filter(delete_flg=False)
        self.context = {
            'teams': teams,
            'positions': positions,
            'user_project_joined': user_project_joined,
        }
        return super().dispatch(request, *args, **kwargs)

    @method_decorator(admin_required)
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)

    @method_decorator(admin_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create(
                username=data.get('username'),
                email=data.get('username'),
                role=data.get('role'),
                is_activate=data.get('is_activate'),
                position=data.get('position'),
                team=data.get('team')
            )
            user.set_password(DEFAULT_PASSWORD)
            user.save()

            input_skills = data.get('skills')
            for skill in json.loads(input_skills):
                user_skill = UserSkill.objects.create(
                    name=skill.get('name'),
                    level=skill.get('level'),
                    years_experience=skill.get('exp')
                )
                user_skill.user.add(user)
                user_skill.save()
            return redirect(reverse_lazy('users:member-list'))
        self.context.update({'form': form})
        return render(request, self.template_name, self.context)


class UserMemberUpdateView(View):
    template_name = 'user/member/member_edit.html'
    form_class = UserMemberCreateUpdateForm

    def dispatch(self, request, *args, **kwargs):
        teams = UserTeam.objects.filter(delete_flg=False)

templates/user/team/team_add.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="col-md-6">
    <div class="content-box-large">
        <div class="panel-heading">
            <div class="panel-title">Create Team Form</div>

            <div class="panel-options">
                <a href="{% url 'users:team-add' %}" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
            </div>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" role="form" method="post" action="{% url 'users:team-add' %}">
                {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
                {% csrf_token %}
                <div class="form-group">
                    <label for="inputName" class="col-sm-2 control-label">Name</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="inputName" placeholder="Name" name="name"
                               value="{{ form.name.value }}">
                        {% if form.name.errors %}
                        <p></p>
                        {% for error in form.name.errors %}
                        <p><strong class="text-danger">{{ error|escape }}</strong></p>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputLeaderName" class="col-sm-2 control-label">Leader</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="inputLeaderName" placeholder="Leader Name"
                               name="leader" value="{{ form.leader.value }}">
                        {% if form.leader.errors %}
                        <p></p>
                        {% for error in form.leader.errors %}
                        <p><strong class="text-danger">{{ error|escape }}</strong></p>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputDescription" class="col-sm-2 control-label">Description</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" id="inputDescription" placeholder="Description"
                                  name="description">{{ form.description.value }}</textarea>
                        {% if form.description.errors %}
                        <p></p>
                        {% for error in form.description.errors %}
                            <p><strong class="text-danger">{{ error|escape }}</strong></p>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/user/team/team_edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="col-md-6">
    <div class="content-box-large">
        <div class="panel-heading">
            <div class="panel-title">Update Team Form</div>

            <div class="panel-options">
                <a href="{% if form %}{% url 'users:team-update' team_id %}{% else %}{% url 'users:team-update' team.id %}{% endif %}"
                   data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
            </div>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" role="form" method="post"
                  action="{% if form %}{% url 'users:team-update' team_id %}{% else %}{% url 'users:team-update' team.id %}{% endif %}">
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% csrf_token %}
            <div class="form-group">
                <label for="inputName" class="col-sm-2 control-label">Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="inputName" placeholder="Name" name="name"
                           value="{% if form %}{{ form.name.value }}{% else %}{{ team.name }}{% endif %}">
                    {% if form.name.errors %}
                    <p></p>
                    {% for error in form.name.errors %}
                    <p><strong class="text-danger">{{ error|escape }}</strong></p>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="inputLeaderName" class="col-sm-2 control-label">Leader</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="inputLeaderName" placeholder="Leader Name"
                           name="leader"
                           value="{% if form %}{{ form.leader.value }}{% else %}{{ team.leader }}{% endif %}">
                    {% if form.leader.errors %}
                    <p></p>
                    {% for error in form.leader.errors %}
                    <p><strong class="text-danger">{{ error|escape }}</strong></p>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="inputDescription" class="col-sm-2 control-label">Description</label>
                <div class="col-sm-10">
                        <textarea class="form-control" id="inputDescription" placeholder="Description"
                                  name="description">{% if form %}{{ form.description.value }}{% else %}{{ team.description }}{% endif %}</textarea>
                    {% if form.description.errors %}
                    <p></p>
                    {% for error in form.description.errors %}
                    <p><strong class="text-danger">{{ error|escape }}</strong></p>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/user/team/team_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="col-md-6">
    <div class="content-box-large">
        <div class="panel-heading">
            <div class="panel-title">Table Positions</div>

            <div class="panel-options">
                <form action="{% url 'users:export' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="export_team" value="1">
                    <button type="submit" class="btn btn-primary glyphicon glyphicon-print" data-rel="collapse"> Export</button>
                </form>
            </div>
        </div>
        <div class="panel-body">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Leader</th>
                </tr>
                </thead>
                <tbody>
                {% for team in teams %}
                <tr>
                    <td>{{ team.id }}</td>
                    <td><a href="{% url 'users:team-update' team.id %}">{{ team.name }}</a></td>
                    <td>{{ team.leader }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="card-footer clearfix">
                <ul class="pagination pagination-sm m-0 float-right">
                    {% if teams.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">«</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ teams.previous_page_number }}">prev</a>
                    </li>
                    {% endif %}
                    <li class="page-item">
                        <a class="current page-link">
                            {{ teams.number }}
                        </a>
                    </li>
                    {% if teams.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ teams.next_page_number }}">next</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ teams.paginator.num_pages }}">»</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}